### ISSUE TITLE
builder error: msvc error

### ISSUE THREAD

**Issue by luatdolphin** [ldedev/SdkBuilder#1]
I tried to build C# lib with this tool, but it seems to be having something wrong. Can you help me with this issue?
```
Building SDK
Reading file conf. sdk
Generate AST for "\src/main.v"
V panic: result not set (cannot compile `C:\Users\Dolphin\Documents\Dev\v\cmd\tools\vast`:
Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32825 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl -w /we4013 /volatile:ms /Fo"C:\Users\Dolphin\AppData\Local\Temp\v_0\vast.12883405189386808164.tmp.c.obj" /F 16777216 /MD /DNDEBUG "C:\Users\Dolphin\AppData\Local\Temp\v_0\vast.12883405189386808164.tmp.c" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt" -I "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared" /DGC_NOT_DLL=1 /DGC_WIN32_THREADS=1 /DGC_THREADS=1 -I "C:\Users\Dolphin\Documents\Dev\v\thirdparty\libatomic_ops" -I "C:\Users\Dolphin\Documents\Dev\v\thirdparty\libgc\include" -I "C:\Users\Dolphin\Documents\Dev\v\thirdparty\cJSON" "C:\Users\Dolphin\Documents\Dev\v/thirdparty/libatomic_ops/atomic_ops.obj" "C:\Users\Dolphin\Documents\Dev\v/thirdparty/libgc/gc.obj" "C:\Users\Dolphin\Documents\Dev\v/thirdparty/cJSON/cJSON.obj" kernel32.lib user32.lib advapi32.lib ws2_32.lib dbghelp.lib ws2_32.lib advapi32.lib /link /NOLOGO /OUT:"C:\Users\Dolphin\Documents\Dev\v\cmd\tools\vast\vast.exe" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\ucrt\X64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\X64" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\lib\X64" /DEBUG:FULL

vast.12883405189386808164.tmp.c
   Creating library C:\Users\Dolphin\Documents\Dev\v\cmd\tools\vast\vast.lib and object C:\Users\Dolphin\Documents\Dev\v\cmd\tools\vast\vast.exp
LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
gc.obj : error LNK2019: unresolved external symbol __imp__CrtDbgReport referenced in function GC_write
C:\Users\Dolphin\Documents\Dev\v\cmd\tools\vast\vast.exe : fatal error LNK1120: 1 unresolved externals

builder error: msvc error

)
v hash: 2ea02f7
6 : v_panic                    ?? : address = 0x1f21f99eaa0
5 : panic_result_not_set       ?? : address = 0x1f21f99e930
4 : src__builder_sdk__construct  ?? : address = 0x1f21f99e830
3 : wmain                      ?? : address = 0x1f21f99eae0
2 : __scrt_common_main_seh     D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
1 : BaseThreadInitThunk        ?? : address = 0x1f21f99ea50
0 : RtlUserThreadStart         ?? : address = 0x1f21f99eb40
```

**Comment by Ddiidev** [comment]
Did you manage to do it with GCC/Clang?
TCC I know it doesn't work, but I haven't investigated it yet.
I'm going to test here with MSVC.

**Comment by luatdolphin** [comment]
> Did you manage to do it with GCC/Clang? TCC I know it doesn't work, but I haven't investigated it yet. I'm going to test here with MSVC.

Yes, I suppose I used GCC

```
Compiling the V library...
-> Name : MySimpleDll
-> Language : csharp
-> Compiler : gcc
-> Production : false
V panic: result not set (Failed to compile the V library | err: Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32825 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```

**Comment by Ddiidev** [comment]
Can you show me your 'sdkbuilder.json' file

**Comment by luatdolphin** [comment]
That's your original file on github, I didn't modify anything, I'm trying to build the example

**Comment by luatdolphin** [comment]
I found the reason, it seems the tool cannot read the json file so it uses the default parameters, instead of msvc it is always gcc

**Comment by Ddiidev** [comment]
I managed to reproduce the error, apparently the V ast generator is not in your V folder, I don't know why.
![image](https://github.com/ldedev/SdkBuilder/assets/7676415/d36c023e-e3a0-4812-bae4-bfff6cf85889)

![image](https://github.com/ldedev/SdkBuilder/assets/7676415/652a99bd-6725-4f29-8ee5-eb8c28e59815)

I recommend that you download Vlang again and follow the installation steps



> I found the reason, it seems the tool cannot read the json file so it uses the default parameters, instead of msvc it is always gcc

I saw the problem here, thank you. I'm going to upload this modification. But look if there is this "vast" folder in the V installation folder

--- edit

this is [commit (#20c387f)](https://github.com/ldedev/SdkBuilder/commit/20c387ff9757aad4bb13a1d411900133b9e9c5b3) see if it worked for you.

**Comment by luatdolphin** [comment]
> I managed to reproduce the error, apparently the V ast generator is not in your V folder, I don't know why. ![image](https://user-images.githubusercontent.com/7676415/283014550-d36c023e-e3a0-4812-bae4-bfff6cf85889.png)
> 
> ![image](https://user-images.githubusercontent.com/7676415/283004102-652a99bd-6725-4f29-8ee5-eb8c28e59815.png)
> 
> I recommend that you download Vlang again and follow the installation steps
> 
> > I found the reason, it seems the tool cannot read the json file so it uses the default parameters, instead of msvc it is always gcc
> 
> I saw the problem here, thank you. I'm going to upload this modification. But look if there is this "vast" folder in the V installation folder
> 
> --- edit
> 
> this is [commit (#20c387f)](https://github.com/ldedev/SdkBuilder/commit/20c387ff9757aad4bb13a1d411900133b9e9c5b3) see if it worked for you.

For vast's problem I rebuilt the tools along with msvc using the command `v -cc msvc build-tools` and put it back into the .disable_autorecompilation file to avoid rebuilding. Similarly, I also rebuilt SdkBuilder with the command `v -cc msvc .`

**Comment by Ddiidev** [comment]
> > I managed to reproduce the error, apparently the V ast generator is not in your V folder, I don't know why. ![image](https://user-images.githubusercontent.com/7676415/283014550-d36c023e-e3a0-4812-bae4-bfff6cf85889.png)
> > 
> > ![image](https://user-images.githubusercontent.com/7676415/283004102-652a99bd-6725-4f29-8ee5-eb8c28e59815.png)
> > 
> > I recommend that you download Vlang again and follow the installation steps
> > 
> > > I found the reason, it seems the tool cannot read the json file so it uses the default parameters, instead of msvc it is always gcc
> > 
> > I saw the problem here, thank you. I'm going to upload this modification. But look if there is this "vast" folder in the V installation folder
> > 
> > --- edit
> > 
> > this is [commit (#20c387f)](https://github.com/ldedev/SdkBuilder/commit/20c387ff9757aad4bb13a1d411900133b9e9c5b3) see if it worked for you.
> 
> For vast's problem I rebuilt the tools along with msvc using the command `v -cc msvc build-tools` and put it back into the .disable_autorecompilation file to avoid rebuilding. Similarly, I also rebuilt SdkBuilder with the command `v -cc msvc .`

Were you able to build the example? Or is it still in error?

**Comment by luatdolphin** [comment]
There were a total of 2 problems that arose during my build process, the first was an error with the build-tools in v-lang, I built these build-tools using the TCC library, and then I built them again by MSVC to solve this problem. The 2nd error is related to reading the JSON file.

**Comment by luatdolphin** [comment]
> Were you able to build the example? Or is it still in error?

Yes, I have built the example already.
