### ISSUE TITLE
Failed do import Library

### ISSUE THREAD

**Issue by luatdolphin** [ldedev/SdkBuilder#2]
After I updated to .Net 8 SDK version. LoadLibrary can't recognize .dll path. So "Failed do import Library". Do you have any ideas to fix this?
```
            DlPtr = Dl.LoadLibrary("./SimpleProjCSInterop/MySimpleDll/MySimpleDll.dll");
            if (DlPtr == nint.Zero)
                throw new Exception("Failed do import Library");
```

**Comment by Ddiidev** [comment]
No, there shouldn't be any problems.
But try to see in the properties of your solution if the dll is marked to copy to the folder.

see the image below (sorry but the print is in Português)

![image](https://github.com/ldedev/SdkBuilder/assets/7676415/d305d6a5-8b81-4640-b296-763641dfead0)

--edit 
my solution is like this (maybe it will help more)

```xml
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net7.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<InvariantGlobalization>true</InvariantGlobalization>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<Platforms>AnyCPU;x86;x64</Platforms>
		<IncludeSymbols>False</IncludeSymbols>
	</PropertyGroup>

	<ItemGroup>
	  <None Update="SimpleProjCSInterop\MySimpleDll\MySimpleDll.dll">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>

```

**Comment by Ddiidev** [comment]
I just changed the version to .net8 and it worked perfectly. Check if the .dll is in the folder.

**Comment by luatdolphin** [comment]
> No, there shouldn't be any problems. But try to see in the properties of your solution if the dll is marked to copy to the folder.
> 
> see the image below (sorry but the print is in Português)
> 
> ![image](https://user-images.githubusercontent.com/7676415/285084965-d305d6a5-8b81-4640-b296-763641dfead0.png)
> 
> --edit my solution is like this (maybe it will help more)
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk">
> 
> 	<PropertyGroup>
> 		<OutputType>Exe</OutputType>
> 		<TargetFramework>net7.0</TargetFramework>
> 		<ImplicitUsings>enable</ImplicitUsings>
> 		<Nullable>enable</Nullable>
> 		<InvariantGlobalization>true</InvariantGlobalization>
> 		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
> 		<Platforms>AnyCPU;x86;x64</Platforms>
> 		<IncludeSymbols>False</IncludeSymbols>
> 	</PropertyGroup>
> 
> 	<ItemGroup>
> 	  <None Update="SimpleProjCSInterop\MySimpleDll\MySimpleDll.dll">
> 	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
> 	  </None>
> 	</ItemGroup>
> 
> </Project>
> ```

![image](https://github.com/ldedev/SdkBuilder/assets/2277080/f3a8cf51-8a06-4441-9312-8db4ee677a0c)
![image](https://github.com/ldedev/SdkBuilder/assets/2277080/a9d110ce-ff28-4fa2-a69b-46780113683a)
![image](https://github.com/ldedev/SdkBuilder/assets/2277080/685b1bfb-d85e-4ca0-8af7-c576f0e4c76e)
I don't understand where the problem is, If I set it to Full path it works perfectly.

**Comment by Ddiidev** [comment]
Does the code snippet like this work?
`DlPtr = Dl.LoadLibrary(Environment.CurrentDirectory + "\\SimpleProjCSInterop\\MySimpleDll\\MySimpleDll.dll");`

If it works, I can make this fix in the code.
